import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

function getStorageClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error('Supabase not configured');
  return createClient(url, key);
}

export async function POST(req: Request) {
  try {
    const { title, content } = (await req.json()) as {
      title: string;
      content: string;
    };

    if (!title || !content) {
      return Response.json({ error: 'Title and content are required' }, { status: 400 });
    }

    const supabase = getStorageClient();
    const id = crypto.randomUUID().slice(0, 12);
    const timestamp = new Date().toISOString().slice(0, 10);
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);

    // Build the markdown file (PDF support can be added later)
    const filename = `report-${slug}-${timestamp}-${id}.md`;
    const fileBuffer = Buffer.from(buildMarkdownFile(title, content), 'utf-8');
    const contentType = 'text/markdown';

    // Upload to Supabase Storage
    const { error: uploadError } = await supabase.storage
      .from('reports')
      .upload(filename, fileBuffer, {
        contentType,
        upsert: false,
      });

    if (uploadError) {
      throw new Error(`Storage upload failed: ${uploadError.message}`);
    }

    // Generate signed URL valid for 24 hours
    const { data: signedData, error: signError } = await supabase.storage
      .from('reports')
      .createSignedUrl(filename, 60 * 60 * 24); // 24 hours

    if (signError || !signedData?.signedUrl) {
      throw new Error(`Failed to create signed URL: ${signError?.message}`);
    }

    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

    return Response.json({
      url: signedData.signedUrl,
      filename,
      format: 'markdown',
      expires: expiresAt,
      title,
    });
  } catch (error) {
    return Response.json(
      { error: error instanceof Error ? error.message : 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function buildMarkdownFile(title: string, content: string): string {
  const date = new Date().toLocaleDateString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'Australia/Sydney',
  });
  return `# ${title}\n\n*Generated by AI Trader Dude — ${date}*\n\n---\n\n${content}\n`;
}

