import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

function getStorageClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error('Supabase not configured');
  return createClient(url, key);
}

export async function POST(req: Request) {
  try {
    const { title, content, format = 'markdown' } = (await req.json()) as {
      title: string;
      content: string;
      format?: 'pdf' | 'markdown';
    };

    if (!title || !content) {
      return Response.json({ error: 'Title and content are required' }, { status: 400 });
    }

    const supabase = getStorageClient();
    const id = crypto.randomUUID().slice(0, 12);
    const timestamp = new Date().toISOString().slice(0, 10);
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);

    // Build the file
    let filename: string;
    let fileBuffer: Buffer;
    let contentType: string;

    if (format === 'pdf') {
      // Attempt PDF generation, fall back to markdown
      try {
        const pdfBuffer = await generatePdf(title, content);
        filename = `report-${slug}-${timestamp}-${id}.pdf`;
        fileBuffer = pdfBuffer;
        contentType = 'application/pdf';
      } catch {
        // PDF generation failed — fall back to markdown
        filename = `report-${slug}-${timestamp}-${id}.md`;
        fileBuffer = Buffer.from(buildMarkdownFile(title, content), 'utf-8');
        contentType = 'text/markdown';
      }
    } else {
      filename = `report-${slug}-${timestamp}-${id}.md`;
      fileBuffer = Buffer.from(buildMarkdownFile(title, content), 'utf-8');
      contentType = 'text/markdown';
    }

    // Upload to Supabase Storage
    const { error: uploadError } = await supabase.storage
      .from('reports')
      .upload(filename, fileBuffer, {
        contentType,
        upsert: false,
      });

    if (uploadError) {
      throw new Error(`Storage upload failed: ${uploadError.message}`);
    }

    // Generate signed URL valid for 24 hours
    const { data: signedData, error: signError } = await supabase.storage
      .from('reports')
      .createSignedUrl(filename, 60 * 60 * 24); // 24 hours

    if (signError || !signedData?.signedUrl) {
      throw new Error(`Failed to create signed URL: ${signError?.message}`);
    }

    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
    const actualFormat = filename.endsWith('.pdf') ? 'pdf' : 'markdown';

    return Response.json({
      url: signedData.signedUrl,
      filename,
      format: actualFormat,
      expires: expiresAt,
      title,
    });
  } catch (error) {
    return Response.json(
      { error: error instanceof Error ? error.message : 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function buildMarkdownFile(title: string, content: string): string {
  const date = new Date().toLocaleDateString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'Australia/Sydney',
  });
  return `# ${title}\n\n*Generated by AI Trader Dude — ${date}*\n\n---\n\n${content}\n`;
}

async function generatePdf(title: string, content: string): Promise<Buffer> {
  // Dynamic import so the app works even without md-to-pdf installed
  const { mdToPdf } = await import('md-to-pdf');
  const markdown = buildMarkdownFile(title, content);
  const result = await mdToPdf(
    { content: markdown },
    {
      pdf_options: {
        format: 'A4',
        margin: { top: '25mm', bottom: '25mm', left: '20mm', right: '20mm' },
      },
    }
  );
  if (!result?.content) throw new Error('PDF generation returned empty result');
  return Buffer.from(result.content);
}
